Add support for RPM format package installs

diff --git a/Install b/Install
--- a/Install
+++ b/Install
@@ -37,12 +37,12 @@ PKG_VER=${VERSION}
 PKG_REL=${RELEASE}
 
 get_available_packages() {
-  for debs in ${SRC}/${SRC_NAME}/releases/${PKG_VER}-${PKG_REL}/*.deb
+  for pkgs in ${SRC}/${SRC_NAME}/releases/${PKG_VER}-${PKG_REL}/*.${SUF}
   do
-    [ "${debs}" == "${SRC}/${SRC_NAME}/releases/${PKG_VER}-${PKG_REL}/*.deb" ] || {
-      for pkg in ${debs}
+    [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/${PKG_VER}-${PKG_REL}/*.${SUF}" ] || {
+      for pkg in ${pkgs}
       do
-        pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}-${PKG_REL}.deb//"` 
+        pkgname=`basename ${pkg} | sed -e "s/_${PKG_VER}-${PKG_REL}.${SUF}//"` 
         PKG_AVAILABLE="${PKG_AVAILABLE} ${pkgname}"
       done
     }
@@ -103,6 +103,18 @@ check_package_names() {
     }
   done
 }
+
+debian=
+have_apt=`type -p apt`
+have_dpkg=`type -p dpkg`
+have_rpm=`type -p rpm`
+have_yum=`type -p yum`
+[ -f /etc/os-release ] && . /etc/os-release
+[ "${ID_LIKE}" == "debian" ] && debian=1
+[ "${debian}" ] || [ -f /etc/debian_version ] && debian=1
+
+SUF=deb
+[ "${debian}" ] || SUF=rpm
 
 get_available_packages
 [ "$PKG_AVAILABLE}" ] || {
@@ -195,20 +207,45 @@ install_selected() {
 
 for PKG_NAME in ${PKG_NAMES}
 do
-  DEB="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb"
-  [ -f "${DEB}" ] || {
-    echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.deb not found."
-    for debs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.deb
+  PKG="${SRC}/${SRC_NAME}/releases/${PKG_VER}/${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF}"
+  [ -f "${PKG}" ] || {
+    echo "${PKG_NAME}_${PKG_VER}-${PKG_REL}.${SUF} not found."
+    for pkgs in ${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}
     do
-      [ "${debs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.deb" ] || {
+      [ "${pkgs}" == "${SRC}/${SRC_NAME}/releases/*/${PKG_NAME}_*.${SUF}" ] || {
         echo "Found existing packages:"
-        echo "${debs}"
+        echo "${pkgs}"
       }
     done
     echo ""
     continue
   }
 
-  echo "Installing ${DEB}"
-  sudo apt install "${DEB}"
+  echo "Installing ${PKG}"
+  if [ "${debian}" ]
+  then
+    if [ "${have_apt}" ]
+    then
+      sudo apt install ${PKG}
+    else
+      if [ "${have_dpkg}" ]
+      then
+        sudo dpkg -i ${PKG}
+      else
+        sudo apt install ${PKG}
+      fi
+    fi
+  else
+    if [ "${have_yum}" ]
+    then
+      sudo yum install ${PKG}
+    else
+      if [ "${have_rpm}" ]
+      then
+        sudo rpm -i ${PKG}
+      else
+        sudo dnf install ${PKG}
+      fi
+    fi
+  fi
 done
diff --git a/pkg/tantra-tutorial/postinst b/pkg/tantra-tutorial/postinst
--- a/pkg/tantra-tutorial/postinst
+++ b/pkg/tantra-tutorial/postinst
@@ -38,8 +38,21 @@ case "$1" in
           DOWNLOAD=1
         fi
         [ "${DOWNLOAD}" ] && {
-          inst=`type -p pip`
-          [ "${inst}" ] || sudo apt-get install python-pip
+          type -p pip > /dev/null || {
+            if type -p apt-get > /dev/null
+            then
+              apt-get -q -y install python-pip
+            else
+              if type -p apt > /dev/null
+              then
+                apt -q -y install python-pip
+              else
+                echo "Unable to locate apt-get or apt"
+                echo "Verify that apt-get or apt is installed"
+                echo "then retry installation of this package."
+              fi
+            fi
+          }
           pip list | grep -F gdown > /dev/null || {
             pip install gdown
           }
